# Numpy

In [ ]:
%pip install numpy

In [2]:
import numpy as np

In [3]:
print(np.array([1, 2, 3, 4]))

[1 2 3 4]


In [4]:
a = np.array([
    [1, 2, 3], 
    [1, 2, 3]
])
b = np.array([[1, 2, 2], [1, 2, 2], [1, 4, 5]])
c = np.array([
    [1, 2], [2, 3]
])

In [5]:
a.dot(b)
# a.dot(c) # error

array([[ 6, 18, 21],
       [ 6, 18, 21]])

In [6]:
a * a

array([[1, 4, 9],
       [1, 4, 9]])

In [7]:
a @ b

array([[ 6, 18, 21],
       [ 6, 18, 21]])

In [8]:
x = np.array([2 ,4 ,5, 6, 10, 11])

x.shape

(6,)

In [9]:
x[4:6]
x[0]
x[-1]
x[1:4:1]
x[2:-1:2]

array([ 5, 10])

In [10]:
np.sum(x)
np.mean(x)

np.float64(6.333333333333333)

In [11]:
y = np.arange(0, 12)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
y.reshape(2, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [13]:
np.zeros(shape=(8, 8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
np.ones(shape=(4, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.repeat(2, 5)

array([2, 2, 2, 2, 2])

In [16]:
np.full(shape=(2, 3), fill_value=2)

array([[2, 2, 2],
       [2, 2, 2]])

In [17]:
b = np.full(shape=(8, 8), fill_value="b")
b[1::2, ::2] = "w"
b[::2, 1::2] = "w"
b

array([['b', 'w', 'b', 'w', 'b', 'w', 'b', 'w'],
       ['w', 'b', 'w', 'b', 'w', 'b', 'w', 'b'],
       ['b', 'w', 'b', 'w', 'b', 'w', 'b', 'w'],
       ['w', 'b', 'w', 'b', 'w', 'b', 'w', 'b'],
       ['b', 'w', 'b', 'w', 'b', 'w', 'b', 'w'],
       ['w', 'b', 'w', 'b', 'w', 'b', 'w', 'b'],
       ['b', 'w', 'b', 'w', 'b', 'w', 'b', 'w'],
       ['w', 'b', 'w', 'b', 'w', 'b', 'w', 'b']], dtype='<U1')

In [18]:
np.random.seed(0)
np.random.randint(2, 5, size=(2, 3))

array([[2, 3, 2],
       [3, 3, 4]], dtype=int32)

In [19]:
np.random.choice([3, 2, 5, 6], p=[0.1, 0.2, 0.2, 0.5], size=(2, 3))

array([[5, 6, 6],
       [5, 6, 6]])

In [20]:
a.T

array([[1, 1],
       [2, 2],
       [3, 3]])

In [21]:
np.delete(a, 0, axis=1)

array([[2, 3],
       [2, 3]])

In [22]:
x = np.random.randint(1, 50, size=20)

In [23]:
x[x < 5]

array([1], dtype=int32)

In [24]:
x[(x < 15) & (x > 10)]
# x[10 < x < 15] # error

array([14], dtype=int32)

In [25]:
x[(x > 10) | (x < 5)].shape

(17,)

In [26]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])

In [27]:
np.stack([a, b], axis=1)

array([[1, 1],
       [2, 2],
       [3, 3]])

In [28]:
np.stack([a, b], axis=0)

array([[1, 2, 3],
       [1, 2, 3]])

In [30]:
np.concatenate([a, b], axis=0)

array([1, 2, 3, 1, 2, 3])